global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backing-shop'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['localhost:7255']

  - job_name: 'prometheus'
    static_configs: